### ISSUE TITLE
Cannot reproduce results for UCR

### ISSUE THREAD

**Issue by SamSamhuns** [ruiking04/CutAddPaste#4]
Again, thank you for the great work. I tried reproducing the results without modifying anything other than some of the pip requirements since I had version issues, but the UCR accuracy is being reported as 0 here. I am using the same configs as provided in the repo without any changes.

The test loss also increases during the training process.

My machine setup

```yaml
    (venv) (p38) user@USER:~/Main/CutAddPaste$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
    (venv) (p38) user@USER:~/Main/CutAddPaste$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
    (venv) (p38) user@USER:~/Main/CutAddPaste$ python --version
Python 3.8.20
    (venv) (p38) user@USER:~/Main/CutAddPaste$ pip freeze
certifi==2024.12.14
charset-normalizer==3.4.1
cmdstanpy==1.2.5
contourpy==1.1.1
cycler==0.12.1
Cython==3.0.11
dill==0.3.9
exceptiongroup==1.2.2
filelock==3.16.1
fonttools==4.55.3
fsspec==2024.12.0
gitdb==4.0.12
GitPython==3.1.44
holidays==0.58
idna==3.10
importlib_resources==6.4.5
iniconfig==2.0.0
Jinja2==3.1.5
joblib==1.4.2
kiwisolver==1.4.7
lightgbm==4.5.0
MarkupSafe==2.1.5
matplotlib==3.7.5
mpmath==1.3.0
networkx==3.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.1.105
packaging==24.2
pandas==2.0.3
patsy==1.0.1
pillow==10.4.0
plotly==5.24.1
pluggy==1.5.0
prophet==1.1.6
py4j==0.10.9.8
pyparsing==3.1.4
pystan==2.19.1.1
pytest==8.3.4
python-dateutil==2.9.0.post0
pytz==2024.2
requests==2.32.3
salesforce-merlion==1.1.1
scikit-learn==1.3.2
scipy==1.10.1
six==1.17.0
smmap==5.0.2
stanio==0.5.1
statsmodels==0.14.1
sympy==1.13.3
tenacity==9.0.0
threadpoolctl==3.5.0
tomli==2.2.1
torch==2.4.1
tqdm==4.67.1
triton==3.0.0
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
zipp==3.20.2
```

The training logs

```yaml
Dataset: UCR
Method:  CutAddPaste
Random Seed:  4
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 35000
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 44795
Data loaded ...
Training started ....

Epoch : 1
Train Loss     : 0.6285	 | 
Valid Loss     : 0.5017	  | 
Test Loss     : 0.5046	  | 


Epoch : 2
Train Loss     : 0.5222	 | 
Valid Loss     : 0.2646	  | 
Test Loss     : 0.2582	  | 


Epoch : 3
Train Loss     : 0.4552	 | 
Valid Loss     : 0.1027	  | 
Test Loss     : 0.1242	  | 


Epoch : 4
Train Loss     : 0.3931	 | 
Valid Loss     : 0.1086	  | 
Test Loss     : 0.0967	  | 


Epoch : 5
Train Loss     : 0.3560	 | 
Valid Loss     : 0.0644	  | 
Test Loss     : 0.0997	  | 


Epoch : 6
Train Loss     : 0.3198	 | 
Valid Loss     : 0.0628	  | 
Test Loss     : 0.1053	  | 


Epoch : 7
Train Loss     : 0.2920	 | 
Valid Loss     : 0.1059	  | 
Test Loss     : 0.1123	  | 


Epoch : 8
Train Loss     : 0.2778	 | 
Valid Loss     : 0.0995	  | 
Test Loss     : 0.1104	  | 


Epoch : 9
Train Loss     : 0.2493	 | 
Valid Loss     : 0.2041	  | 
Test Loss     : 0.1132	  | 


Epoch : 10
Train Loss     : 0.2367	 | 
Valid Loss     : 0.1317	  | 
Test Loss     : 0.1135	  | 


Epoch : 11
Train Loss     : 0.2194	 | 
Valid Loss     : 0.1122	  | 
Test Loss     : 0.1124	  | 


Epoch : 12
Train Loss     : 0.2050	 | 
Valid Loss     : 0.1134	  | 
Test Loss     : 0.1149	  | 


Epoch : 13
Train Loss     : 0.2034	 | 
Valid Loss     : 0.0588	  | 
Test Loss     : 0.1155	  | 


Epoch : 14
Train Loss     : 0.1872	 | 
Valid Loss     : 0.1121	  | 
Test Loss     : 0.1158	  | 


Epoch : 15
Train Loss     : 0.1838	 | 
Valid Loss     : 0.0693	  | 
Test Loss     : 0.1107	  | 


Epoch : 16
Train Loss     : 0.1762	 | 
Valid Loss     : 0.1010	  | 
Test Loss     : 0.1185	  | 


Epoch : 17
Train Loss     : 0.1747	 | 
Valid Loss     : 0.0650	  | 
Test Loss     : 0.1170	  | 


Epoch : 18
Train Loss     : 0.1723	 | 
Valid Loss     : 0.1117	  | 
Test Loss     : 0.1250	  | 


Epoch : 19
Train Loss     : 0.1672	 | 
Valid Loss     : 0.0787	  | 
Test Loss     : 0.1187	  | 


Epoch : 20
Train Loss     : 0.1659	 | 
Valid Loss     : 0.0971	  | 
Test Loss     : 0.1250	  | 


Epoch : 21
Train Loss     : 0.1551	 | 
Valid Loss     : 0.1413	  | 
Test Loss     : 0.1186	  | 


Epoch : 22
Train Loss     : 0.1497	 | 
Valid Loss     : 0.0611	  | 
Test Loss     : 0.1200	  | 


Epoch : 23
Train Loss     : 0.1502	 | 
Valid Loss     : 0.1113	  | 
Test Loss     : 0.1211	  | 


Epoch : 24
Train Loss     : 0.1438	 | 
Valid Loss     : 0.1059	  | 
Test Loss     : 0.1185	  | 


Epoch : 25
Train Loss     : 0.1388	 | 
Valid Loss     : 0.0777	  | 
Test Loss     : 0.1238	  | 


Epoch : 26
Train Loss     : 0.1354	 | 
Valid Loss     : 0.1080	  | 
Test Loss     : 0.1268	  | 


Epoch : 27
Train Loss     : 0.1394	 | 
Valid Loss     : 0.1800	  | 
Test Loss     : 0.1146	  | 


Epoch : 28
Train Loss     : 0.1365	 | 
Valid Loss     : 0.1248	  | 
Test Loss     : 0.1187	  | 


Epoch : 29
Train Loss     : 0.1361	 | 
Valid Loss     : 0.0899	  | 
Test Loss     : 0.1175	  | 


Epoch : 30
Train Loss     : 0.1262	 | 
Valid Loss     : 0.0652	  | 
Test Loss     : 0.1218	  | 


Epoch : 31
Train Loss     : 0.1306	 | 
Valid Loss     : 0.0648	  | 
Test Loss     : 0.1272	  | 


Epoch : 32
Train Loss     : 0.1258	 | 
Valid Loss     : 0.0843	  | 
Test Loss     : 0.1280	  | 


Epoch : 33
Train Loss     : 0.1178	 | 
Valid Loss     : 0.0900	  | 
Test Loss     : 0.1284	  | 


Epoch : 34
Train Loss     : 0.1186	 | 
Valid Loss     : 0.1012	  | 
Test Loss     : 0.1293	  | 


Epoch : 35
Train Loss     : 0.1265	 | 
Valid Loss     : 0.1073	  | 
Test Loss     : 0.1308	  | 


Epoch : 36
Train Loss     : 0.1180	 | 
Valid Loss     : 0.1701	  | 
Test Loss     : 0.1253	  | 


Epoch : 37
Train Loss     : 0.1208	 | 
Valid Loss     : 0.1134	  | 
Test Loss     : 0.1276	  | 


Epoch : 38
Train Loss     : 0.1133	 | 
Valid Loss     : 0.1424	  | 
Test Loss     : 0.1190	  | 


Epoch : 39
Train Loss     : 0.1160	 | 
Valid Loss     : 0.1185	  | 
Test Loss     : 0.1281	  | 


Epoch : 40
Train Loss     : 0.1116	 | 
Valid Loss     : 0.1364	  | 
Test Loss     : 0.1178	  | 


Epoch : 41
Train Loss     : 0.1062	 | 
Valid Loss     : 0.1216	  | 
Test Loss     : 0.1296	  | 


Epoch : 42
Train Loss     : 0.1128	 | 
Valid Loss     : 0.0581	  | 
Test Loss     : 0.1194	  | 


Epoch : 43
Train Loss     : 0.1101	 | 
Valid Loss     : 0.1594	  | 
Test Loss     : 0.1410	  | 


Epoch : 44
Train Loss     : 0.1109	 | 
Valid Loss     : 0.0624	  | 
Test Loss     : 0.1319	  | 


Epoch : 45
Train Loss     : 0.1158	 | 
Valid Loss     : 0.0671	  | 
Test Loss     : 0.1358	  | 


Epoch : 46
Train Loss     : 0.1104	 | 
Valid Loss     : 0.1087	  | 
Test Loss     : 0.1285	  | 


Epoch : 47
Train Loss     : 0.0997	 | 
Valid Loss     : 0.0682	  | 
Test Loss     : 0.1325	  | 


Epoch : 48
Train Loss     : 0.1057	 | 
Valid Loss     : 0.1112	  | 
Test Loss     : 0.1289	  | 


Epoch : 49
Train Loss     : 0.0993	 | 
Valid Loss     : 0.0932	  | 
Test Loss     : 0.1306	  | 


Epoch : 50
Train Loss     : 0.0955	 | 
Valid Loss     : 0.0768	  | 
Test Loss     : 0.1284	  | 

......................

Epoch : 291
Train Loss     : 0.0267	 | 
Valid Loss     : 0.0655	  | 
Test Loss     : 0.1708	  | 


Epoch : 292
Train Loss     : 0.0308	 | 
Valid Loss     : 0.1060	  | 
Test Loss     : 0.1712	  | 


Epoch : 293
Train Loss     : 0.0290	 | 
Valid Loss     : 0.0663	  | 
Test Loss     : 0.1715	  | 


Epoch : 294
Train Loss     : 0.0329	 | 
Valid Loss     : 0.0658	  | 
Test Loss     : 0.1719	  | 


Epoch : 295
Train Loss     : 0.0307	 | 
Valid Loss     : 0.0658	  | 
Test Loss     : 0.1706	  | 


Epoch : 296
Train Loss     : 0.0261	 | 
Valid Loss     : 0.2039	  | 
Test Loss     : 0.1701	  | 


Epoch : 297
Train Loss     : 0.0329	 | 
Valid Loss     : 0.0659	  | 
Test Loss     : 0.1706	  | 


Epoch : 298
Train Loss     : 0.0257	 | 
Valid Loss     : 0.1447	  | 
Test Loss     : 0.1715	  | 


Epoch : 299
Train Loss     : 0.0277	 | 
Valid Loss     : 0.0654	  | 
Test Loss     : 0.1712	  | 


Epoch : 300
Train Loss     : 0.0306	 | 
Valid Loss     : 0.0654	  | 
Test Loss     : 0.1708	  | 


################## Training is Done! #########################
Test affiliation-metrics
Test precision: 0.3501  | 	Test recall: 0.3505

Test RAP F1
Test F1: 0.0000  | 	Test precision: 0.0000  | 	Test recall: 0.0000

Test PA F1
Test F1: 0.0000  | 	Test precision: 0.0000  | 	Test recall: 0.0000

Test PW F1
Test F1: 0.0000  | 	Test precision: 0.0000  | 	Test recall: 0.0000

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
UCR metrics:
 accuracy: {'accuracy': 0.0}

affiliation metrics:
 Precision: 0.35014
 Recall:    0.35050
F1 Scores: 0.35032
Revised-point-adjusted metrics:
 Precision: 0.00000
 Recall:    0.00000
F1 score:  0.00000
 Point-adjusted metrics:
 Precision: 0.00000
 Recall:    0.00000
 F1 score:  0.00000
 Point-wise metrics:
 Precision: 0.00000
 Recall:    0.00000
F1 Scores:  0.00000
NAB Scores:
 NAB Score (balanced):       -0.04635
 NAB Score (high precision): -0.09270
 NAB Score (high recall):    -0.03090
seed: 4 
config setup:

dataset:UCR
input_channels:1
kernel_size:8
stride:1
final_out_channels:64
project:2
dropout:0.45
features_len:10
window_size:64
time_step:16
num_epoch:300
beta1:0.9
beta2:0.99
lr:0.0003
weight:0.0005
drop_last:False
batch_size:512
trend_rate:0.01
rate:1
cut_rate:12
detect_nu:0.001
threshold_determine:one-anomaly
Training time is : 0:00:34.777396
```
